# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=250)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.Project')),
            ],
            options={
                'ordering': ['project', 'position'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectcompetitor',
            unique_together=set([('project', 'position')]),
        ),
    ]
