# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170921_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompetitor',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
