# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170921_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcompetitor',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectCompetitor'),
        ),
    ]
