# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectcompetitor_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcompetitor',
            unique_together=set([]),
        ),
    ]
