# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170921_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcompetitor',
            name='target',
        ),
    ]
