# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_projectcompetitor_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompetitor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='project.Project'),
        ),
    ]
